// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwdienubaapqxoypnqsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3ZGllbnViYWFwcXhveXBucXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDg3ODksImV4cCI6MjA2NjkyNDc4OX0.i92mFjT9h1h-pAyqGNXtcH4_99dl4zVqaL0bpkkWRb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});